name = "singularity-exam-feed"
main = "src/index.js"
compatibility_date = "2024-11-01"

# Pull the source feed every 3 hours.
[triggers]
crons = ["0 */3 * * *"]

[[kv_namespaces]]
binding = "FEED"
id = "affc2e6a09044f06a4b6c13c04c68029"
